apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Kube-State metrics
  - ksm.yaml
  - ksm-alerts.yaml
  # Node exporter required by Kubecost
  # ( deployed as a DaemonSet )
  - node-exporter.yaml
  - node-exporter-alerts.yaml
