apiVersion: v1
kind: Secret
metadata:
  name: gitops-whisper-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/shivanshs9/whisper-notes
