apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base

helmCharts:
  - name: cert-manager
    releaseName: cert-manager
    repo: https://charts.jetstack.io
    includeCRDs: true
    version: 1.14.4
    namespace: cert-manager
    valuesFile: ./cm-values.yaml

helmGlobals:
  chartHome: .cache
