apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- secret.yaml

namePrefix: whisper-notes-
namespace: default

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: grpc-backend
    app.kubernetes.io/created-by: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whisper-notes-grpc
    app.kubernetes.io/part-of: whisper-notes
- pairs:
    app.kubernetes.io/version: latest

images:
- name: grpc-backend
  # CHANGEME: replace with GCP Artifact Registry
  newName: europe-north1-docker.pkg.dev/${PROJECT}/services/whisper-notes-backend
  newTag: main-5d9cf2b
