apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-db
spec:
  dataFrom:
    - extract:
        key: whisper-prod-service-notes-db
  refreshInterval: 15s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-secret-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: sec-whisper-backend-db
