apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trusted-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: selfsigned-ca
  subject:
    organizations:
      - ACME Inc.
    organizationalUnits:
      - Widgets
  secretName: selfsigned-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
