apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: rt-argocd
  namespace: argocd
spec:
  parentRefs:
    - name: public-gateway
      namespace: default
  hostnames:
    - "argocd.shivanshs9.me"
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
