apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base
  - appset
  - ingress.yaml

helmCharts:
  - name: argo-cd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm
    includeCRDs: true
    version: 6.7.5
    namespace: argocd
    valuesFile: ./values.yaml

patches:
  - path: patch-cm-kustomize.yaml
  - path: patch-notif-cm.yaml

helmGlobals:
  chartHome: .cache
