apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: argocd.shivanshs9.me # CHANGEME: Desired ArgoCD URL

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  context: |
    argocdUrl: argocd.shivanshs9.me # CHANGEME: Desired ArgoCD URL
