apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

namePrefix: whisper-notes-
namespace: default

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/created-by: controller-manager
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whisper-notes-frontend
    app.kubernetes.io/part-of: whisper-notes
- pairs:
    app.kubernetes.io/version: latest

    # CHANGEME: replace with GCP Artifact Registry
images:
- name: frontend
- name: frontend:latest
  newName: europe-north1-docker.pkg.dev/${GCP_PROJECT}/services/whisper-notes-frontend
  newTag: main-3354b15
