name: "Docker build & push to Artifact Registry"
description: "Builds the docker image and pushes it to Google Artifact Registry"
on:
  workflow_call:
    inputs:
      repo:
        description: "Repository name"
        required: true
        type: string
      registry:
        description: "Google Artifact registry"
        required: false
        default: "docker.pkg.dev"
        type: string
      dockerfile:
        description: "Dockerfile path"
        required: false
        default: "Dockerfile"
        type: string
      context:
        description: "Docker context"
        required: false
        default: "."
        type: string
      build_args:
        description: "Docker build args"
        required: false
        default: ""
        type: string
    outputs:
      imageid:
        description: "Image ID"
        value: ${{ jobs.push.outputs.imageid }}
      tag:
        description: "Image tag"
        value: ${{ jobs.push.outputs.tag }}
jobs:
  push:
    name: "Build & Push"
    runs-on: ubuntu-latest
    outputs:
      imageid: ${{ steps.build.outputs.imageid }}
      tag: ${{ steps.vars.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - name: Docker login to Google Cloud
        id: vars
        run: |
          echo "$B64_GOOGLE_KEY" | docker login -u _json_key_base64 --password-stdin https://$REGISTRY
          sha_short=$(git rev-parse --short HEAD)
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          tag="${branch}-${sha_short}"
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "full_tag=$REGISTRY/$GCP_PROJECT/$REPO:$tag" >> $GITHUB_OUTPUT
        shell: bash
        env:
          GCP_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
          B64_GOOGLE_KEY: ${{ secrets.GCLOUD_SECRET_KEY }}
          REGISTRY: ${{ inputs.registry }}
          REPO: ${{ inputs.repo }}
      - name: Check image
        id: image_exists
        continue-on-error: true
        uses: cloudposse/github-action-docker-image-exists@main
        with:
          registry: ${{ inputs.registry }}
          image_name: ${{ secrets.GCLOUD_PROJECT }}/${{ inputs.repo }}
          tag: ${{ steps.vars.outputs.tag }}
      - uses: docker/setup-buildx-action@v3
        if: steps.image_exists.outcome == 'failure'
      - uses: docker/build-push-action@v5
        if: steps.image_exists.outcome == 'failure'
        id: build
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          labels: |
            ci.run_id=${{ github.run_id }}
          build-args: |
            ${{ vars.BUILD_ARGS }}
            ${{ inputs.build_args }}
          tags: |
            ${{ steps.vars.outputs.full_tag }}
