name: CD

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  push-backend:
    name: Build backend
    uses: ./.github/workflows/build-push-gcloud.yaml
    with:
      repo: services/whisper-notes-backend
      dockerfile: backend.Dockerfile
      registry: europe-north1-docker.pkg.dev
    secrets: inherit
  push-frontend:
    name: Build frontend
    uses: ./.github/workflows/build-push-gcloud.yaml
    with:
      repo: services/whisper-notes-frontend
      dockerfile: frontend.Dockerfile
      registry: europe-north1-docker.pkg.dev
      # CHANGEME: Backend URL to use during frontend build
      build_args: |
        VITE_GRPC_BACKEND: https://whisper-notes.shivanshs9.me/api
    secrets: inherit
